#!/usr/bin/env bash

ROOT="$(dirname "${BASH_SOURCE[0]}")/../"
cd $ROOT
. ./scripts/util/cargo-args.sh

while (($#)); do
	case "$1" in
		-d | --debug) DEBUG=true ;; 
	esac
	shift
done

if [[ -n $DEBUG ]] then
	BUILD+=("${DEBUG_ARGS[@]}")
else
	BUILD+=("${RELEASE_ARGS[@]}")
fi

cargo "${BUILD[@]}"
