#!/usr/bin/env bash

ROOT="$(dirname "${BASH_SOURCE[0]}")/../"
cd $ROOT

. ./scripts/util/cargo-args

wasm-pack build                 \
	--out-dir "./build/wasm-pack" \
	--target web                  \
	--release --no-typescript     \
	$ROOT                         \
	--target-dir "./build/target" \
	-Zpanic-immediate-abort -Zbuild-std=std,panic_abort
