#!/usr/bin/env bash

ROOT="$(dirname "${BASH_SOURCE[0]}")/../"
cd $ROOT
. ./scripts/util/cargo-args.sh
BUILD+=(--target wasm32-unknown-unknown)

while (($#)); do
	case "$1" in
		-d | --debug) DEBUG=true ;; 
	esac
	shift
done

if [[ -n $DEBUG ]] then
	BUILD+=("${DEBUG[@]}")
else
	BUILD+=("${RELEASE[@]}")
fi

cargo "${BUILD[@]}"

wasm-bindgen --target web       \
	--out-dir "./build/wasm-pack" \
	--no-typescript               \
	./build/target/wasm32-unknown-unknown/release/stowball.wasm
